version: '3'

services:

  nginx:
    container_name: pw_composer-server
    image: nginx:1.19.6-alpine
    restart: unless-stopped
    ports:
      - "8030:80"
    volumes:
      - .:/app
      - ./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  app:
    container_name: pw_composer-php
    image: vcaballerosalle/pwii-php-fpm
    restart: unless-stopped
    ports:
      - "9030:9001"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    container_name: pw_composer-db
    image: mysql:8.0.25
    restart: unless-stopped
    ports:
      - "3330:3306"
    env_file:
      - .env

  admin:
    container_name: pw_composer-admin
    image: adminer:4.8.1-standalone
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db

